### ISSUE TITLE
toolbar example ?

### ISSUE THREAD

**Issue by KnIfER** [gammasoft71/Examples_Win32#2]

**Comment by KnIfER** [comment]
还是纯win32开发吧，就是差个进度条和黑暗菜单条。

![image](https://user-images.githubusercontent.com/11593903/115958973-bea86c00-a544-11eb-81b6-4cccf5f438d9.png)

**Comment by gammasoft71** [comment]
here : [ToolBars](https://github.com/gammasoft71/Examples_Win32/tree/master/Win32.Gui/MenusAndToolbars/Toolbar)
