### ISSUE TITLE
Can you add more examples of Console Functions?

### ISSUE THREAD

**Issue by hwhsu1231** [gammasoft71/Examples_Win32#5]
Win32 Console Functions: https://docs.microsoft.com/en-us/windows/console/console-functions

Demonstrate functions in the above link as more as possible.

**Comment by gammasoft71** [comment]
You can find some examples here :

[Console](https://github.com/gammasoft71/Examples_Win32/tree/master/Win32.System/Console)
[ConsoleColor](https://github.com/gammasoft71/Examples_Win32/tree/master/Win32.System/ConsoleColor)
