### ISSUE TITLE
Unicode support example

### ISSUE THREAD

**Issue by florrika** [gammasoft71/Examples_Win32#7]
I tried on my own but it's uhh not unicoding

**Comment by gammasoft71** [comment]
Hi,

You can try with [HelloWorldStaticText](https://github.com/gammasoft71/Examples_Win32/tree/master/Win32.Gui/HelloWorlds/HelloWorldStaticText) example.
Replace line `39` the text `L"Hello, World!"` by `L"\u0021\u0645\u0631\u062d\u0628\u0627\u064b \u0623\u064a\u0647\u0627 \u0627\u0644\u0639\u0627\u0644\u0645"`.

build and run.
And you see the following output with unicode text.

![image](https://github.com/user-attachments/assets/edd397bb-16a0-4c2a-9ca2-4ec0222c27da)

**Comment by florrika** [comment]
I was writing in just unicode "кнопка 1 нажата 0 раз" with all these CreateWindowExW and SendMessageW and it wasn't working but after encoding with js it all worked flawless
